# Generated by Django 5.2.1 on 2025-05-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
