# Generated by Django 5.2.1 on 2025-05-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='tienda.cliente'),
        ),
    ]
