# Generated by Django 5.2.1 on 2025-05-29 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_administrador_first_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='id_admin',
        ),
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
