# Generated by Django 5.2.1 on 2025-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_administrador_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='first_login',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='user',
        ),
        migrations.AddField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(default='hola', max_length=100),
        ),
        migrations.AddField(
            model_name='administrador',
            name='estado',
            field=models.CharField(default='No verificado', max_length=100),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_admin',
            field=models.CharField(default=12, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
