# Generated by Django 5.2.1 on 2025-05-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_administrador_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
