# Generated by Django 5.2.1 on 2025-05-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='rut',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
